// AESGCM.swift
// Tier 1 algorithm: AES-256-GCM (NIST FIPS 197 + NIST SP 800-38D).
//
// This is the *only* Tier 1 cipher in v0.0.2. ML-KEM (post-quantum
// key encapsulation), ML-DSA (signatures) and ChaCha20-Poly1305
// arrive in subsequent sprints. Each lives in its own file under
// Sources/AegisCrypto/Tier1/.
//
// Implementation notes:
//   - We use Apple's CryptoKit `AES.GCM` for the primitive. CryptoKit
//     uses CommonCrypto / CoreCrypto under the hood; on Apple silicon
//     these are hardware-accelerated and FIPS-validated.
//   - Keys MUST be exactly 256 bits (32 bytes). We refuse other sizes
//     loudly rather than silently truncating or padding.
//   - Nonce is always randomly generated by CryptoKit when `encrypt`
//     is called without one. Test code (KATs) uses `encrypt(_:key:nonce:)`
//     to inject NIST-supplied nonces.
//   - The optional `additionalData` field (associated data, AEAD-style)
//     is supported but not yet used by the messenger; it's there so
//     that future protocol changes can authenticate metadata (sender
//     id, message index, etc.) without re-shipping the cipher code.

import CryptoKit
import Foundation

/// AES-256-GCM authenticated encryption with associated data.
///
/// Tier 1 algorithm. Standardised in NIST FIPS 197 (AES) and
/// NIST SP 800-38D (GCM mode). Test vectors from the NIST CAVP
/// program (gcmEncryptExtIV256.rsp) are exercised by
/// `AESGCMKATTests` in the test target.
public struct AESGCM: Encryption {

    public static let methodId = "tier1.aes-256-gcm"

    public static let methodMetadata = EncryptionMethod(
        id: AESGCM.methodId,
        displayName: "AES-256-GCM",
        description: "Authenticated encryption with associated data. "
            + "Hardware-accelerated on Apple silicon. Standardised by NIST.",
        tier: .tier1Approved,
        standardReference: "NIST FIPS 197 + NIST SP 800-38D"
    )

    public var method: EncryptionMethod { Self.methodMetadata }

    /// Required key size in bits. Constant-named for grep-ability.
    public static let requiredKeyBits = 256

    public init() {}

    // MARK: - Encrypt (random nonce)

    /// Encrypt `plaintext` under `key` with a fresh random 96-bit nonce
    /// drawn by CryptoKit's CSPRNG.
    ///
    /// - Throws: `AegisError.invalidKey` if `key` is not exactly 256 bits.
    public func encrypt(
        _ plaintext: Data,
        key: SymmetricKey
    ) throws -> EncryptedPayload {
        try validate(key: key)
        return try seal(plaintext: plaintext, key: key, nonce: nil, ad: nil)
    }

    // MARK: - Encrypt (explicit nonce, for KATs and protocol code)

    /// Encrypt with a caller-supplied nonce. Typically only test code
    /// or wire-format code that derives a deterministic nonce calls this.
    /// Random-nonce encryption is the default; reusing a `(key, nonce)`
    /// pair across two messages destroys GCM's security guarantees.
    ///
    /// - Parameters:
    ///   - plaintext: bytes to encrypt
    ///   - key: 256-bit symmetric key
    ///   - nonce: 96-bit nonce (12 bytes); MUST be unique per `key`
    ///   - additionalData: optional bytes to authenticate but not encrypt
    /// - Throws: `AegisError.invalidKey`, `AegisError.invalidNonce`,
    ///   or `AegisError.underlying`
    public func encrypt(
        _ plaintext: Data,
        key: SymmetricKey,
        nonce: AES.GCM.Nonce,
        additionalData: Data? = nil
    ) throws -> EncryptedPayload {
        try validate(key: key)
        return try seal(plaintext: plaintext, key: key, nonce: nonce, ad: additionalData)
    }

    // MARK: - Decrypt

    public func decrypt(
        _ payload: EncryptedPayload,
        key: SymmetricKey
    ) throws -> Data {
        // Refuse mismatched method ids — never decrypt with the wrong
        // algorithm. This is the protection that lets us safely register
        // multiple algorithms and route per-payload.
        guard payload.methodId == AESGCM.methodId else {
            throw AegisError.unsupportedMethod(id: payload.methodId)
        }

        try validate(key: key)

        // Validate nonce length explicitly. AES.GCM.Nonce(data:) will
        // throw on wrong length but we want to surface a clear error.
        guard payload.nonce.count == 12 else {
            throw AegisError.invalidNonce(
                reason: "AES-GCM nonce must be 12 bytes; got \(payload.nonce.count)"
            )
        }

        let nonce: AES.GCM.Nonce
        do {
            nonce = try AES.GCM.Nonce(data: payload.nonce)
        } catch {
            throw AegisError.invalidNonce(reason: "\(error)")
        }

        // Validate tag length. AES-GCM authentication tag is 128 bits.
        guard payload.tag.count == 16 else {
            throw AegisError.ciphertextCorrupted
        }

        let sealedBox: AES.GCM.SealedBox
        do {
            sealedBox = try AES.GCM.SealedBox(
                nonce: nonce,
                ciphertext: payload.ciphertext,
                tag: payload.tag
            )
        } catch {
            throw AegisError.ciphertextCorrupted
        }

        // Always go through the `authenticating:` overload, even when
        // `additionalData` is nil. Empty AAD is mathematically equivalent
        // to no AAD in AES-GCM (AAD length is authenticated, and length 0
        // is length 0 either way). Doing this consistently sidesteps a
        // macOS 26 / CryptoKit issue where the no-AAD `open(_:using:)`
        // overload triggers a debug trap on authentication failure
        // instead of throwing CryptoKitError.authenticationFailure.
        let aad = payload.additionalData ?? Data()
        do {
            return try AES.GCM.open(sealedBox, using: key, authenticating: aad)
        } catch CryptoKitError.authenticationFailure {
            throw AegisError.authenticationFailed
        } catch {
            // Any other CryptoKit error is also treated as auth failure
            // for safety — we never return partial plaintext.
            throw AegisError.authenticationFailed
        }
    }

    // MARK: - Key derivation helper

    /// Derive a 256-bit AES-GCM key from a passphrase via HKDF-SHA-256.
    ///
    /// HKDF (RFC 5869) is the right pattern for turning a low-entropy
    /// passphrase or a shared secret into a fixed-size key. The salt
    /// is intentionally fixed in this overload — for per-conversation
    /// keys, callers should pass a per-conversation salt instead.
    ///
    /// - Important: HKDF is NOT a password-stretching function. Don't
    ///   feed it a user-typed password; feed it a high-entropy input
    ///   (a random secret, a Diffie-Hellman shared secret, etc.). For
    ///   user passwords, layer Argon2id on top — that's a v0.0.4 task.
    public static func deriveKey(
        from secret: Data,
        salt: Data = Data("aegis.tier1.aes-256-gcm.v1".utf8),
        info: Data = Data()
    ) -> SymmetricKey {
        let inputKey = SymmetricKey(data: secret)
        return HKDF<SHA256>.deriveKey(
            inputKeyMaterial: inputKey,
            salt: salt,
            info: info,
            outputByteCount: 32   // 256 bits
        )
    }

    // MARK: - Internals

    private func validate(key: SymmetricKey) throws {
        guard key.bitCount == AESGCM.requiredKeyBits else {
            throw AegisError.invalidKey(
                reason: "AES-256-GCM requires a \(AESGCM.requiredKeyBits)-bit key; got \(key.bitCount)"
            )
        }
    }

    private func seal(
        plaintext: Data,
        key: SymmetricKey,
        nonce: AES.GCM.Nonce?,
        ad: Data?
    ) throws -> EncryptedPayload {
        // Mirror of decrypt's policy: always pass the `authenticating:`
        // form (with empty Data() when no AAD), so seal/open use the
        // identical CryptoKit code path.
        let aad = ad ?? Data()
        let sealedBox: AES.GCM.SealedBox
        do {
            if let n = nonce {
                sealedBox = try AES.GCM.seal(plaintext, using: key, nonce: n, authenticating: aad)
            } else {
                sealedBox = try AES.GCM.seal(plaintext, using: key, authenticating: aad)
            }
        } catch {
            throw AegisError.underlying(description: "\(error)")
        }

        return EncryptedPayload(
            methodId: AESGCM.methodId,
            nonce: Data(sealedBox.nonce),
            ciphertext: sealedBox.ciphertext,
            tag: sealedBox.tag,
            // Preserve nil-vs-empty distinction at the payload level so
            // serialised payloads don't gain a spurious `additionalData`
            // field when none was requested.
            additionalData: ad
        )
    }
}
